services:
- type: web
  name: MelodyScout Ohio
  runtime: node
  repo: https://github.com/JPSAUD501/MelodyScout
  plan: free
  envVars:
  - fromGroup: MELODY SCOUT ENV
  region: ohio
  buildCommand: yarn install --production
  startCommand: yarn start:prod
  healthCheckPath: /health
version: "1"